edition = "2018"
max_width = 90
use_field_init_shorthand = true
use_try_shorthand = true
use_small_heuristics = "Max"
format_code_in_doc_comments = true
imports_granularity= "Crate"
wrap_comments = true
format_macro_matchers = true
format_macro_bodies = true
